repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
    -   id: mypy
        # NOTEL: This should mirror [tool.mypy] in pyproject.toml 
        args: [fastrepl, tests, --exclude, .venv, --explicit-package-bases, --ignore-missing-imports, --enable-incomplete-feature, Unpack]
        language: system
        pass_filenames: false
        stages: [pre-push]