version: '3'

tasks:
  install: POETRY_VIRTUALENVS_IN_PROJECT=true poetry install
  
  run: poetry run python3 {{.CLI_ARGS}}
  run:example:basic: poetry run jupyter nbconvert --to notebook --inplace --execute examples/basic.ipynb
  run:example:all: poetry run jupyter nbconvert --to notebook --inplace --execute examples/*.ipynb

  test: poetry run pytest -m "not todo" -n auto --benchmark-disable {{.CLI_ARGS}}
  test:ci: poetry run pytest -m "not todo" -n auto --benchmark-disable --cov=fastrepl --cov-report xml:cov.xml
  test:todo: poetry run pytest -m "todo" -n auto -v --benchmark-disable
  test:bench: poetry run pytest --benchmark-only tests/benchmark
  test:cov: poetry run pytest --benchmark-disable --cov=fastrepl --cov-report=term-missing -n auto {{.CLI_ARGS}}

  todo: rg "TODO" --hidden
  fmt: poetry run black fastrepl tests
  lint: poetry run mypy fastrepl tests
  clean: rm -f .local/*.gv .local/*.png

  metric:add: 
    cmds:
      - evaluate-cli create {{.CLI_ARGS}} --module_type "metric" --output_dir spaces --dataset_name=None --organization fastrepl
      - sh scripts/space.sh {{.CLI_ARGS}}
      - git submodule add https://huggingface.co/spaces/fastrepl/{{.CLI_ARGS}} spaces/{{.CLI_ARGS}}

  add: poetry add {{.CLI_ARGS}}
  add:dev: poetry add {{.CLI_ARGS}} --group dev
  add:doc: poetry add {{.CLI_ARGS}} --group doc
  sync: poetry lock --no-update && poetry install --sync
  
  fix:setuptools: poetry run pip install --force-reinstall -U setuptools && poetry run pip install --force-reinstall -U pip

  pre-publish: rm -rf dist && poetry config pypi-token.pypi $PYPI_API_KEY && poetry publish --no-cache --build --dry-run
  publish: poetry publish

  doc:install: poetry run pip install -r docs/requirements.txt
  doc:build: rm -rf docs/_build && poetry run sphinx-build -b html docs docs/_build/html
  doc:watch: rm -rf docs/_build && poetry run sphinx-autobuild docs/ docs/_build/html --open-browser --watch $(git rev-parse --show-toplevel)/fastrepl/
